import { Platform, StyleSheet } from 'react-native';
import { Colors, FontSize, FontWeight, Radius, Spacing } from '../../theme';

export const styles = StyleSheet.create({
  pendingEditsBadge: {
    position: 'absolute',
    top: 2,
    right: 2,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: Colors.danger,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 3,
  },
  pendingEditsBadgeText: { color: Colors.white, fontSize: 10, fontWeight: '700' },
  pinnedBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
    paddingHorizontal: 14,
    backgroundColor: '#FFF7E6',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.border,
  },
  pinnedBannerLabel: { fontSize: 11, fontWeight: '700', color: Colors.primary },
  pinnedBannerText: { fontSize: 14, color: Colors.textPrimary, marginTop: 1 },
  // iter-169 web parity: conversation message area uses the dedicated
  // `chatWallpaper` token (#F5F1E7) instead of the app body color.
  container: { flex: 1, backgroundColor: Colors.chatWallpaper },
  chatHeader: {
    // iter-174: two-row header layout for legibility (Row 1 = identity,
    // Row 2 = action buttons). Header is now a column.
    minHeight: 130,
    backgroundColor: Colors.headerBg,
    paddingHorizontal: 8,
    paddingTop: 14,
    paddingBottom: 8,
    flexDirection: 'column',
    gap: 6,
  },
  chatHeaderTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 0,
    minWidth: 0,
  },
  chatHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
  },
  chatHeaderIdentity: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
  },
  chatHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 4,
    flexShrink: 0,
  },
  headerIconButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#E4B53B',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 8,
    overflow: 'hidden',
  },
  headerAvatarWrap: {
    width: 42,
    height: 42,
    marginHorizontal: 8,
  },
  headerOnlineDot: {
    position: 'absolute',
    right: -1,
    bottom: -1,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#22C55E',
    borderWidth: 2,
    borderColor: Colors.headerBg,
  },
  // iter-109 Diary mode — blue avatar circle housing the book icon.
  headerAvatarDiary: {
    backgroundColor: Colors.diary,
  },
  headerAvatarImage: {
    width: 42,
    height: 42,
    borderRadius: 21,
  },
  headerAvatarText: {
    fontSize: 18,
    fontWeight: FontWeight.bold,
    color: '#3D2A00',
  },
  headerTextWrap: {
    flex: 1,
    minWidth: 0,
    flexShrink: 1,
    paddingRight: 8,
  },
  chatHeaderTitle: {
    // iter-174: bigger, bolder, more legible. Title now has full row width.
    fontSize: 20,
    fontWeight: FontWeight.bold,
    color: Colors.white,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerFilterIcon: { marginRight: 6 },
  chatHeaderSubtitle: {
    // iter-174: brighter presence subtitle. Was 0.78 alpha → tougher to
    // read on a brown background; bumped to 0.92 + slightly larger font.
    marginTop: 3,
    fontSize: 14,
    color: 'rgba(255,255,255,0.92)',
    fontWeight: FontWeight.medium,
  },
  chatHeaderCityTime: {
    // iter-319: peer city + local time, sits between name and last-seen.
    marginTop: 2,
    fontSize: 12.5,
    color: 'rgba(255,255,255,0.78)',
    fontWeight: FontWeight.medium,
  },
  encryptionBanner: {
    minHeight: 34,
    backgroundColor: '#DFF1DB',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  // iter-109 in-chat search bar — yellow-bordered input under the
  // header. Matches the web app's "Search diary messages…" look.
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  // iter-220 in-conversation search highlight + ▲/▼ navigation bar.
  searchNavBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  searchNavTextWrap: { flex: 1 },
  searchNavInput: {
    fontSize: FontSize.base,
    color: Colors.textPrimary,
    paddingVertical: 0,
  },
  searchNavCount: {
    fontSize: FontSize.xs,
    color: Colors.textSecondary,
    marginTop: 1,
  },
  searchNavBtn: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 17,
    backgroundColor: Colors.background,
  },
  searchInput: {
    flex: 1,
    fontSize: FontSize.base,
    color: Colors.textPrimary,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: '#E4B53B',
    backgroundColor: '#FFFCF4',
  },
  encryptionBannerText: {
    fontSize: 12,
    color: '#2A7C48',
    fontWeight: FontWeight.medium,
  },
  // ─── Multi-select forwarding banner (iter-99) ───
  // Sits between the encryption banner and the messages list. Mirrors
  // WhatsApp-style action bar with cancel-on-left + Forward-on-right.
  multiSelectBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.primary,
    paddingHorizontal: Spacing.base,
    paddingVertical: 10,
    gap: 14,
  },
  multiSelectCountText: {
    color: Colors.white,
    fontSize: FontSize.base,
    fontWeight: FontWeight.semibold,
    flex: 1,
  },
  multiSelectForwardBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  multiSelectForwardIcon: { marginRight: 6 },
  multiSelectForwardLabel: {
    color: Colors.white,
    fontWeight: FontWeight.semibold,
    fontSize: FontSize.sm,
  },
  multiSelectForwardLabelDim: { color: 'rgba(255,255,255,0.5)' },
  loadingWrap: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  listContent: {
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 20,
  },
  loadEarlierBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    gap: 6,
    marginBottom: 12,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: Radius.pill,
    backgroundColor: Colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Colors.primary,
  },
  loadEarlierText: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: Colors.primary,
  },
  locationRequestBannerWrap: {
    paddingHorizontal: 12,
    paddingTop: 10,
  },
  deletionReqBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    backgroundColor: '#FFF1F0',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#FFD6D2',
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  deletionReqInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flex: 1,
  },
  deletionReqText: {
    flex: 1,
    fontSize: 12.5,
    fontWeight: FontWeight.medium,
    color: Colors.textPrimary,
  },
  deletionReqActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  deletionReqBtn: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: Radius.md,
    minHeight: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deletionReqDecline: {
    backgroundColor: 'transparent',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Colors.border,
  },
  deletionReqDeclineText: {
    fontSize: 12.5,
    fontWeight: FontWeight.semibold,
    color: Colors.textSecondary,
  },
  deletionReqDelete: {
    backgroundColor: Colors.tickRed,
  },
  deletionReqDeleteText: {
    fontSize: 12.5,
    fontWeight: FontWeight.bold,
    color: '#fff',
  },
  offlineBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: Colors.tickYellow,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  offlineBannerText: {
    fontSize: 12,
    fontWeight: FontWeight.semibold,
    color: Colors.headerBg,
  },
  shareOnceCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    alignSelf: 'center',
    width: '86%',
    marginVertical: 6,
    padding: 12,
    borderRadius: 14,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: 'rgba(233,181,59,0.5)',
  },
  shareOnceIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E9B53B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shareOnceTitle: { fontSize: 14, fontWeight: '700', color: '#1c1c1e' },
  shareOnceHint: { fontSize: 12, color: '#E9B53B', fontWeight: '700', marginTop: 2 },
  shareOnceCardWrap: { alignSelf: 'center', width: '86%', marginVertical: 6 },
  shareOnceGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    padding: 16,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  shareOnceGradientSel: { borderColor: '#E9B53B' },
  shareOnceEyeCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#C026D3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shareOnceTitleWhite: { fontSize: 15, fontWeight: '700', color: '#fff', lineHeight: 21 },
  shareOnceThumbWrap: { width: 44, height: 44, borderRadius: 10, overflow: 'hidden', backgroundColor: '#000' },
  shareOnceThumb: { width: 44, height: 44 },
  shareOnceThumbPlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(0,0,0,0.25)' },
  shareOnceReactionsRow: { flexDirection: 'row', gap: 4, alignSelf: 'center', width: '86%', marginTop: -2, marginBottom: 6 },
  shareOnceReactionChip: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 12, backgroundColor: '#fff', borderWidth: 1, borderColor: 'rgba(0,0,0,0.12)', gap: 2 },
  shareOnceReactionChipMine: { borderColor: '#E9B53B', backgroundColor: 'rgba(233,181,59,0.12)' },
  shareOnceReactionEmoji: { fontSize: 12 },
  shareOnceReactionCount: { fontSize: 10, color: '#6b7280', fontWeight: '600' },

  dayChipWrap: {
    alignItems: 'center',
    marginVertical: 8,
  },
  dayChipText: {
    fontSize: 11,
    color: '#766C5E',
    backgroundColor: 'rgba(247, 241, 224, 0.95)',
    paddingHorizontal: 14,
    paddingVertical: 5,
    borderRadius: 14,
    overflow: 'hidden',
  },
  systemPillWrap: {
    alignItems: 'center',
    marginVertical: 6,
    paddingHorizontal: 32,
  },
  systemPillText: {
    fontSize: 12,
    color: '#5C5346',
    backgroundColor: 'rgba(247, 241, 224, 0.95)',
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderRadius: 14,
    overflow: 'hidden',
    textAlign: 'center',
    lineHeight: 17,
  },
  empty: {
    alignItems: 'center',
    paddingTop: 60,
  },
  emptyText: {
    fontSize: FontSize.sm,
    color: Colors.textSecondary,
  },
  unavailableWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: Spacing.xl,
    gap: Spacing.base,
  },
  unavailableTitle: {
    fontSize: FontSize.lg,
    fontWeight: FontWeight.bold,
    color: Colors.textPrimary,
  },
  unavailableText: {
    fontSize: FontSize.sm,
    color: Colors.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
  },
  replyPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: Spacing.base,
    paddingVertical: 10,
    backgroundColor: Colors.surface,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  replyAccent: { width: 3, height: 32, borderRadius: 2, backgroundColor: Colors.primary },
  // editAccent — orange/warning accent so the editing pill is visually
  // distinct from the green reply pill. Same dimensions/shape.
  editAccent: { backgroundColor: Colors.warning ?? '#F59E0B' },
  replyLabel: { fontSize: 11, fontWeight: FontWeight.bold, color: Colors.primary },
  replyText: { fontSize: 13, color: Colors.textSecondary, marginTop: 2 },
  uploadBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: Spacing.base,
    paddingVertical: 10,
    backgroundColor: Colors.primaryLight,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  uploadText: { fontSize: FontSize.sm, color: Colors.textPrimary, fontWeight: FontWeight.medium },
  pendingImageBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginHorizontal: Spacing.sm,
    marginBottom: 6,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 12,
  },
  pendingImageThumb: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: Colors.border,
  },
  pendingImageHint: {
    flex: 1,
    fontSize: FontSize.sm,
    color: Colors.textSecondary,
  },
  pendingImageRemove: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pendingImagesBar: {
    marginHorizontal: Spacing.sm,
    marginBottom: 6,
    paddingVertical: 8,
    paddingHorizontal: 8,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 12,
  },
  pendingImagesStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingRight: 4,
    paddingTop: 4,
  },
  pendingThumbWrap: {
    width: 48,
    height: 48,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  pendingThumbActive: {
    borderColor: Colors.primary,
  },
  pendingThumbRemove: {
    position: 'absolute',
    top: -7,
    right: -7,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(0,0,0,0.65)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pendingThumbEdit: {
    position: 'absolute',
    bottom: -7,
    left: -7,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(10,132,255,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pendingThumbCaptionDot: {
    position: 'absolute',
    bottom: 3,
    right: 3,
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: Colors.primary,
    borderWidth: 1,
    borderColor: Colors.white,
  },
  pendingThumbScan: {
    position: 'absolute',
    bottom: -7,
    right: -7,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(34,197,94,0.95)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pendingThumbScanSuggest: {
    borderWidth: 2,
    borderColor: '#FFD166',
    width: 24,
    height: 24,
    borderRadius: 12,
    bottom: -9,
    right: -9,
  },
  docSuggestChip: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 6,
    marginTop: 8,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 14,
    backgroundColor: 'rgba(34,197,94,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(34,197,94,0.4)',
  },
  docSuggestText: { fontSize: 12, fontWeight: '600', color: Colors.primary },
  pendingThumbScannedBadge: {
    position: 'absolute',
    top: -7,
    left: -7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    paddingHorizontal: 5,
    height: 16,
    borderRadius: 8,
    backgroundColor: 'rgba(34,197,94,0.95)',
  },
  pendingThumbScannedText: {
    color: '#fff',
    fontSize: 9,
    fontWeight: '700',
  },
  composerToolsWrap: {
    backgroundColor: '#F1E7D6',
    borderTopWidth: 1,
    borderTopColor: '#D9C9AE',
  },
  formatPreviewWrap: {
    backgroundColor: '#F7EFE0',
    borderTopWidth: 1,
    borderTopColor: '#E4D6BE',
    paddingHorizontal: 18,
    paddingVertical: 8,
    // iter-466: never let the live formatting preview grow unbounded. A very
    // large draft (e.g. a pasted log containing "[b…]"/"[i…]" that trips the
    // rich-text regex) would otherwise expand this block and push the composer
    // TextInput off-screen — leaving the user unable to edit/send/clear it.
    maxHeight: 96,
  },
  formatPreviewLabel: {
    fontSize: 10,
    fontWeight: FontWeight.bold,
    color: Colors.textMuted,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  formatPreviewText: {
    fontSize: FontSize.sm,
    lineHeight: 20,
    color: Colors.textPrimary,
  },
  formatPreviewBold: { fontWeight: FontWeight.bold },
  formatPreviewItalic: { fontStyle: 'italic' },
  formatPreviewUnderline: { textDecorationLine: 'underline' },
  inlineFormatHint: {
    flex: 1,
    fontSize: 11,
    color: Colors.textMuted,
    fontWeight: FontWeight.medium,
  },
  inlineItalicGlyph: { fontStyle: 'italic' },
  inlineUnderlineGlyph: { textDecorationLine: 'underline' },
  swatchGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 4,
  },
  swatchCell: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  swatchCellLight: {
    borderColor: '#D4CCBC',
  },
  formatBubbleWrap: {
    alignItems: 'center',
    paddingBottom: 6,
    paddingHorizontal: 12,
  },
  formatBubble: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2A2A2A',
    borderRadius: 12,
    paddingHorizontal: 4,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 6,
      },
      android: { elevation: 5 },
      default: {},
    }),
  },
  formatBubbleBtn: {
    width: 42,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  formatBubbleText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: FontWeight.bold,
  },
  formatBubbleDivider: {
    width: StyleSheet.hairlineWidth,
    height: 20,
    backgroundColor: 'rgba(255,255,255,0.25)',
  },
  composerDock: {
    backgroundColor: '#EFE3CF',
  },
  suspensionBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 14,
    paddingHorizontal: Spacing.base,
    backgroundColor: '#fee2e2',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#fca5a5',
  },
  suspensionBannerText: {
    flex: 1,
    fontSize: FontSize.sm,
    color: '#7f1d1d',
    fontWeight: FontWeight.medium,
    lineHeight: 20,
  },
  composerToolbarRow: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 18,
    paddingVertical: 6,
  },
  composerToolBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  composerToolBadge: {
    fontSize: 10,
    fontWeight: FontWeight.bold,
    color: Colors.textSecondary,
    marginLeft: 1,
  },
  composerBulletDot: {
    marginRight: 1,
  },
  composerToolBtnActive: {
    backgroundColor: '#FFF7DE',
  },
  composerToolText: {
    fontSize: 22,
    color: Colors.textPrimary,
    fontWeight: FontWeight.medium,
  },
  composerToolTextActive: {
    color: Colors.primary,
    fontWeight: FontWeight.bold,
  },
  colorPickerWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 2,
  },
  colorChip: {
    marginRight: 8,
  },
  colorChipSelected: {
    transform: [{ scale: 1.02 }],
  },
  colorChipInner: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  colorChipInnerLight: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D4CCBC',
  },
  colorChipInnerSelected: {
    borderColor: '#E5D8C2',
  },
  colorChipLabel: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: FontWeight.bold,
  },
  colorChipLabelDark: {
    color: Colors.textSecondary,
  },
  inputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingHorizontal: 8,
    paddingTop: 6,
    paddingBottom: 3,
    gap: 4,
    backgroundColor: '#EFE3CF',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#D9C9AE',
  },
  input: {
    flex: 1,
    minHeight: 38,
    maxHeight: 120,
    backgroundColor: '#FBF7F0',
    paddingHorizontal: 13,
    paddingVertical: 9,
    borderRadius: 14,
    fontSize: 13,
    lineHeight: 17,
    color: Colors.textPrimary,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#D7C4A5',
  },
  inputBold: {
    fontWeight: FontWeight.bold,
  },
  sendBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 2,
  },
  scheduleBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#EFE7D6',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 6,
  },
  sendBtnSpacer: {
    width: 36,
    height: 36,
  },
  webToolbarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingTop: 2,
    paddingBottom: 6,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(175, 145, 94, 0.28)',
    backgroundColor: '#EFE3CF',
  },
  webToolBtn: {
    width: 34,
    height: 30,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.58)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(175, 145, 94, 0.22)',
  },
  webToolBtnDisabled: {
    opacity: 0.45,
  },
  webToolBtnActive: {
    backgroundColor: Colors.primaryLight,
    borderColor: Colors.primary,
  },
  webToolFormatActive: {
    color: Colors.primary,
  },
  webToolGifLabel: {
    fontSize: 11,
    fontWeight: FontWeight.bold,
    color: Colors.textSecondary,
    letterSpacing: 0.2,
  },
  recordingRow: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 10 },
  recCancelBtn: { width: 46, height: 46, borderRadius: 23, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FDE2E2' },
  recIndicator: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: '#F8F2E7',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#E7DAC2',
  },
  recWaveWrap: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 3 },
  recWaveBar: { width: 4, borderRadius: 3, backgroundColor: Colors.primary },
  recWaveBarPaused: { opacity: 0.35 },
  recTimer: { fontSize: FontSize.base, fontWeight: FontWeight.bold, color: Colors.textPrimary, fontVariant: ['tabular-nums'] as any },
  recPauseBtn: { width: 46, height: 46, borderRadius: 23, alignItems: 'center', justifyContent: 'center', backgroundColor: '#EEE4D1' },
  recSendBtn: { width: 46, height: 46, borderRadius: 23, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.primary },
  flexOne: { flex: 1 },
  chiefToast: {
    position: 'absolute',
    left: 24,
    right: 24,
    bottom: 96,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(20,20,20,0.92)',
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderRadius: 12,
  },
  chiefToastEmoji: { fontSize: 20 },
  chiefToastText: { flex: 1, color: '#FFFFFF', fontSize: 15, fontWeight: '600' },
});
